### PR TITLE
Feature: SDI printf support

### PR DESCRIPTION
**Pull request by UCSIG**
This adds the command `sdi-printf` to enable the SDI virtual serial port function introduced in the WCH-LinkUtility v1.80. It is supported by WCH-LinkE and was added to WCH-LinkUtility in v1.80.
With this feature, the WCH-LinkE dongle can be used to read data from the debug interface of the mcu and redirect it to the serial port of the WCH-LinkE. Now, printf can be used without the UART peripheral of the mcu, only by using the mcu's internal debug module and the WCH-LinkE dongle.
To use this feature, use an adapted _write function in the mcu's code, as in [this](https://github.com/openwch/ch32v003/tree/main/EVT/EXAM/SDI_Printf/SDI_Printf) example.
Then, enable sdi printf functionality with this option and open the serial port of the WCH-LinkE.

### CODE REVIEW

**Comment by UCSIG** [comment]
Indeed, that would be very cool if the shell/serial port printing could also be implemented into wlink.  
However, currently I don't have enough time to do that... If you could implement the watch feature, that would be amazing!

**Comment by andelf** [comment]
Got a weekend. I'll start work on this.

**Comment by andelf** [comment]
I've polished the implementation.

- Use the name sdi-print instead of sdi-printf
- add "no-detach" for sdi-print enable
- use subcommands instead of args

**Comment by andelf** [comment]
Thanks for the help. merged.

**Pull request merged**
