### PR TITLE
enhance ci

### PR DESCRIPTION
**Pull request by hathach**
similar to https://github.com/ch32-rs/wchisp/pull/49, this PR
- build and upload artifact per commit
- upload release asset per release
- merge nightly release to ci.yml for easier maintanence

PS: please consider to make an release after this, just so we got a milstone to update arduino IDE tool.

### CODE REVIEW

**Comment by hathach** [comment]
@andelf sorry for bumping this up, this is rather similar to wchisp;s PR. Please let me know if you need any changes. Thank you.

**Review by andelf — APPROVED** [review]

**Comment by andelf** [comment]
Thanks. Apologies for the late reply.

I'll schedule a new release later today.

**Comment by hathach** [comment]
superb !! thank you very much

**Comment by andelf** [comment]
The latest version of wlink (v0.0.9) has been released. 
You can find it at <https://github.com/ch32-rs/wlink/releases/tag/v0.0.9>.

**Comment by andelf** [comment]
The CI workflow works like a charm!👍

**Comment by hathach** [comment]
Thank you, numbered release make thing easier to incorporate this to other platforms :)

**Pull request merged**
